// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartMenu.Infrastructure.Data;

#nullable disable

namespace SmartMenu.Infrastructure.Migrations
{
    [DbContext(typeof(SmartMenuDbContext))]
    partial class SmartMenuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductPromotion", b =>
                {
                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("PromotionId")
                        .HasColumnType("bigint");

                    b.HasKey("ProductId", "PromotionId")
                        .HasName("PK__ProductP__51208431EB70CD6A");

                    b.HasIndex("PromotionId");

                    b.ToTable("ProductPromotions", (string)null);
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("ActorUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("success");

                    b.HasKey("AuditId")
                        .HasName("PK__AuditLog__A17F239822EC341C");

                    b.HasIndex("ActorUserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.Category", b =>
                {
                    b.Property<long>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Categori__19093A0BFC2D362C");

                    b.HasIndex(new[] { "CategoryName" }, "UQ__Categori__8517B2E01CB8EF77")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.Device", b =>
                {
                    b.Property<long>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DeviceId"));

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("offline");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.HasKey("DeviceId")
                        .HasName("PK__Devices__49E123115742C4AA");

                    b.HasIndex("StoreId");

                    b.HasIndex(new[] { "Identifier" }, "UQ__Devices__821FB019133F69C8")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.ErrorLog", b =>
                {
                    b.Property<long>("ErrorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ErrorId"));

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContextJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool>("Resolved")
                        .HasColumnType("bit");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ErrorId")
                        .HasName("PK__ErrorLog__35856A2AA970834C");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.InventorySyncLog", b =>
                {
                    b.Property<long>("SyncId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SyncId"));

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProcessedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SyncId")
                        .HasName("PK__Inventor__7E50DEC6A3D88DB1");

                    b.HasIndex("ProductId");

                    b.ToTable("InventorySyncLogs");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.MenuTemplate", b =>
                {
                    b.Property<long>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TemplateId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("LayoutJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("TemplateId")
                        .HasName("PK__MenuTemp__F87ADD276CF965A9");

                    b.HasIndex("CreatedBy");

                    b.ToTable("MenuTemplates");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.Payment", b =>
                {
                    b.Property<long>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasDefaultValue("VND")
                        .IsFixedLength();

                    b.Property<string>("ExternalRef")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("initiated");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__9B556A38E11CE235");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.Playlist", b =>
                {
                    b.Property<long>("PlaylistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PlaylistId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("draft");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("PlaylistId")
                        .HasName("PK__Playlist__B30167A07A7682DC");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.PlaylistItem", b =>
                {
                    b.Property<long>("PlaylistItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PlaylistItemId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("DurationSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<long>("PlaylistId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TemplateInstanceId")
                        .HasColumnType("bigint");

                    b.HasKey("PlaylistItemId")
                        .HasName("PK__Playlist__1910CEADDFCA5B34");

                    b.HasIndex("ProductId");

                    b.HasIndex("TemplateInstanceId");

                    b.HasIndex(new[] { "PlaylistId", "DisplayOrder" }, "UQ_Playlist_Order")
                        .IsUnique();

                    b.ToTable("PlaylistItems");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.PosPriceSyncLog", b =>
                {
                    b.Property<long>("SyncId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SyncId"));

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProcessedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SyncId")
                        .HasName("PK__PosPrice__7E50DEC6A7D561B4");

                    b.HasIndex("ProductId");

                    b.ToTable("PosPriceSyncLogs");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductId"));

                    b.Property<string>("Availability")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("available");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("SKU");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("ProductId")
                        .HasName("PK__Products__B40CC6CD51EFF7A3");

                    b.HasIndex("CategoryId");

                    b.HasIndex(new[] { "Sku" }, "UQ__Products__CA1ECF0DEE4B6DCE")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.ProductPriceVersion", b =>
                {
                    b.Property<long>("PriceVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PriceVersionId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasDefaultValue("VND")
                        .IsFixedLength();

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("manual");

                    b.HasKey("PriceVersionId")
                        .HasName("PK__ProductP__BFA73867D8939E39");

                    b.HasIndex("CreatedBy");

                    b.HasIndex(new[] { "ProductId", "EffectiveFrom", "EffectiveTo" }, "IX_PPV_ProductTime");

                    b.ToTable("ProductPriceVersions");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.ProductStock", b =>
                {
                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("in_stock");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("ProductId")
                        .HasName("PK__ProductS__B40CC6CDFB580CE6");

                    b.ToTable("ProductStock", (string)null);
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.Promotion", b =>
                {
                    b.Property<long>("PromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PromotionId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("amount");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PromotionId")
                        .HasName("PK__Promotio__52C42FCF370CD647");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.Role", b =>
                {
                    b.Property<long>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RoleId"));

                    b.Property<string>("Permissions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE1A59C7FB97");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__8A2B616031E4DC05")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.Schedule", b =>
                {
                    b.Property<long>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ScheduleId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("PlaylistId")
                        .HasColumnType("bigint");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Recurrence")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ScheduleId")
                        .HasName("PK__Schedule__9C8A5B4968C9CB56");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PlaylistId");

                    b.HasIndex(new[] { "DeviceId", "StartTime", "EndTime", "Priority" }, "IX_Schedules_DeviceTime");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.Store", b =>
                {
                    b.Property<long>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StoreId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<long?>("ManagerId")
                        .HasColumnType("bigint");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("StoreId")
                        .HasName("PK__Stores__3B82F101EA1BA0AD");

                    b.HasIndex("ManagerId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.StoreUser", b =>
                {
                    b.Property<long>("StoreUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StoreUserId"));

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("StoreUserId")
                        .HasName("PK__StoreUse__F769D91D1F1A0631");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "StoreId", "UserId" }, "UQ_StoreUser")
                        .IsUnique();

                    b.ToTable("StoreUsers");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.TemplateInstance", b =>
                {
                    b.Property<long>("TemplateInstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TemplateInstanceId"));

                    b.Property<string>("BindingJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint");

                    b.HasKey("TemplateInstanceId")
                        .HasName("PK__Template__F20561FFB2A545D1");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TemplateId");

                    b.ToTable("TemplateInstances");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C0CF06111");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534ABA70512")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProductPromotion", b =>
                {
                    b.HasOne("SmartMenu.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PP_Product");

                    b.HasOne("SmartMenu.Domain.Entities.Promotion", null)
                        .WithMany()
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PP_Promo");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("SmartMenu.Domain.Entities.User", "ActorUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ActorUserId")
                        .HasConstraintName("FK_AuditLogs_User");

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.Device", b =>
                {
                    b.HasOne("SmartMenu.Domain.Entities.Store", "Store")
                        .WithMany("Devices")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Devices_Stores");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.InventorySyncLog", b =>
                {
                    b.HasOne("SmartMenu.Domain.Entities.Product", "Product")
                        .WithMany("InventorySyncLogs")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InvSync_Product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.MenuTemplate", b =>
                {
                    b.HasOne("SmartMenu.Domain.Entities.User", "CreatedByNavigation")
                        .WithMany("MenuTemplates")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_MenuTemplates_User");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.Playlist", b =>
                {
                    b.HasOne("SmartMenu.Domain.Entities.User", "CreatedByNavigation")
                        .WithMany("Playlists")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Playlists_User");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.PlaylistItem", b =>
                {
                    b.HasOne("SmartMenu.Domain.Entities.Playlist", "Playlist")
                        .WithMany("PlaylistItems")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PI_Playlist");

                    b.HasOne("SmartMenu.Domain.Entities.Product", "Product")
                        .WithMany("PlaylistItems")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_PI_Product");

                    b.HasOne("SmartMenu.Domain.Entities.TemplateInstance", "TemplateInstance")
                        .WithMany("PlaylistItems")
                        .HasForeignKey("TemplateInstanceId")
                        .HasConstraintName("FK_PI_TemplateInstance");

                    b.Navigation("Playlist");

                    b.Navigation("Product");

                    b.Navigation("TemplateInstance");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.PosPriceSyncLog", b =>
                {
                    b.HasOne("SmartMenu.Domain.Entities.Product", "Product")
                        .WithMany("PosPriceSyncLogs")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PosSync_Product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.Product", b =>
                {
                    b.HasOne("SmartMenu.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Products_Category");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.ProductPriceVersion", b =>
                {
                    b.HasOne("SmartMenu.Domain.Entities.User", "CreatedByNavigation")
                        .WithMany("ProductPriceVersions")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_PPV_User");

                    b.HasOne("SmartMenu.Domain.Entities.Product", "Product")
                        .WithMany("ProductPriceVersions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PPV_Product");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.ProductStock", b =>
                {
                    b.HasOne("SmartMenu.Domain.Entities.Product", "Product")
                        .WithOne("ProductStock")
                        .HasForeignKey("SmartMenu.Domain.Entities.ProductStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProductStock_Product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.Schedule", b =>
                {
                    b.HasOne("SmartMenu.Domain.Entities.User", "CreatedByNavigation")
                        .WithMany("Schedules")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Schedules_User");

                    b.HasOne("SmartMenu.Domain.Entities.Device", "Device")
                        .WithMany("Schedules")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Schedules_Device");

                    b.HasOne("SmartMenu.Domain.Entities.Playlist", "Playlist")
                        .WithMany("Schedules")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Schedules_Playlist");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Device");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.Store", b =>
                {
                    b.HasOne("SmartMenu.Domain.Entities.User", "Manager")
                        .WithMany("Stores")
                        .HasForeignKey("ManagerId")
                        .HasConstraintName("FK_Stores_Manager");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.StoreUser", b =>
                {
                    b.HasOne("SmartMenu.Domain.Entities.Store", "Store")
                        .WithMany("StoreUsers")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_StoreUsers_Store");

                    b.HasOne("SmartMenu.Domain.Entities.User", "User")
                        .WithMany("StoreUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_StoreUsers_User");

                    b.Navigation("Store");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.TemplateInstance", b =>
                {
                    b.HasOne("SmartMenu.Domain.Entities.User", "CreatedByNavigation")
                        .WithMany("TemplateInstances")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_TemplateInstances_User");

                    b.HasOne("SmartMenu.Domain.Entities.MenuTemplate", "Template")
                        .WithMany("TemplateInstances")
                        .HasForeignKey("TemplateId")
                        .IsRequired()
                        .HasConstraintName("FK_TemplateInstances_Template");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.User", b =>
                {
                    b.HasOne("SmartMenu.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.Device", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.MenuTemplate", b =>
                {
                    b.Navigation("TemplateInstances");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.Playlist", b =>
                {
                    b.Navigation("PlaylistItems");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.Product", b =>
                {
                    b.Navigation("InventorySyncLogs");

                    b.Navigation("PlaylistItems");

                    b.Navigation("PosPriceSyncLogs");

                    b.Navigation("ProductPriceVersions");

                    b.Navigation("ProductStock");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.Store", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("StoreUsers");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.TemplateInstance", b =>
                {
                    b.Navigation("PlaylistItems");
                });

            modelBuilder.Entity("SmartMenu.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("MenuTemplates");

                    b.Navigation("Playlists");

                    b.Navigation("ProductPriceVersions");

                    b.Navigation("Schedules");

                    b.Navigation("StoreUsers");

                    b.Navigation("Stores");

                    b.Navigation("TemplateInstances");
                });
#pragma warning restore 612, 618
        }
    }
}
